// server.js — Local Node.js Bridge for Flow Auto Generator
// HTTP API (port 3500) + WebSocket Server
// Role: Trung gian giữa n8n workflow và Chrome Extension

const express = require('express');
const http = require('http');
const { WebSocketServer, WebSocket } = require('ws');
const cors = require('cors');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 3500;
const QUEUE_FILE = path.join(__dirname, 'queue.json');
const LOG_FILE = path.join(__dirname, 'bridge.log');

// STATE
// ==========================================
let extensionSocket = null;
let jobQueue = [];
let completedJobs = [];
let failedJobs = [];
let currentJob = null;
let paused = false;
let jobCounter = 0;

// Load persisted queue
function loadQueue() {
  try {
    if (fs.existsSync(QUEUE_FILE)) {
      const data = JSON.parse(fs.readFileSync(QUEUE_FILE, 'utf8'));
      jobQueue = data.queue || [];
      completedJobs = data.completed || [];
      failedJobs = data.failed || [];
      jobCounter = data.counter || 0;
      log('📂 Loaded queue: ' + jobQueue.length + ' pending, ' + completedJobs.length + ' completed');
    }
  } catch (e) {
    log('⚠️ Could not load queue: ' + e.message);
  }
}

function saveQueue() {
  try {
    fs.writeFileSync(QUEUE_FILE, JSON.stringify({
      queue: jobQueue,
      completed: completedJobs.slice(0, 100),
      failed: failedJobs.slice(0, 100),
      counter: jobCounter
    }, null, 2));
  } catch (e) {
    log('⚠️ Could not save queue: ' + e.message);
  }
}

function log(msg) {
  const ts = new Date().toISOString();
  const line = '[' + ts + '] ' + msg;
  console.log(line);
  try {
    fs.appendFileSync(LOG_FILE, line + '\n');
  } catch (e) {}
}

// ==========================================
// EXPRESS HTTP API
// ==========================================
const app = express();
app.use(cors());
app.use(express.json());

// Health check
app.get('/', (req, res) => {
  res.json({
    name: 'Flow Auto Bridge',
    version: '1.0.0',
    extensionConnected: extensionSocket !== null && extensionSocket.readyState === WebSocket.OPEN,
    currentJob: currentJob ? { id: currentJob.id, sceneId: currentJob.sceneId, status: currentJob.status } : null,
    queueLength: jobQueue.length,
    completedCount: completedJobs.length,
    failedCount: failedJobs.length,
    paused: paused
  });
});

// Submit new job — called by n8n
app.post('/generate', (req, res) => {
  // Support both Object {...} and Array [{...}] payloads from N8N
  const body = Array.isArray(req.body) ? req.body[0] : req.body;
  const { row_id, rowId, projectId, sceneId, character, prompt, callbackUrl, driveFolderId, images, action } = body || {};
  
  const finalRowId = row_id || rowId || null;

  if (!prompt && action !== 'upload_only' && action !== 'create_project') {
    return res.status(400).json({ error: 'Missing required field: prompt' });
  }

  jobCounter++;
  const job = {
    id: (projectId || 'proj') + '_' + (sceneId || 'scene') + '_' + jobCounter + '_' + Date.now(),
    rowId: finalRowId,
    projectId: projectId || null,
    sceneId: sceneId || 'scene_' + String(jobCounter).padStart(3, '0'),
    character: character || '',
    prompt: prompt || '',
    images: images || [],
    action: action || 'generate',
    callbackUrl: callbackUrl || null,
    driveFolderId: driveFolderId || null,
    status: 'QUEUED',
    createdAt: Date.now()
  };

  jobQueue.push(job);
  saveQueue();
  log('📥 New job queued: ' + job.id + (images?.length ? ' [' + images.length + ' images]' : '') + ' — Action: ' + job.action);

  // Try to dispatch immediately
  dispatchNext();

  res.json({
    success: true,
    jobId: job.id,
    rowId: finalRowId,
    folderId: driveFolderId,
    position: jobQueue.length,
    message: 'Job queued successfully'
  });
});

// Dedicated endpoint to create project and optionally upload images and generate character image
app.post('/create-project', async (req, res) => {
  const body = Array.isArray(req.body) ? req.body[0] : req.body;
  const { rowId, row_id, images, character, characterName, prompt, characterPrompt, callbackUrl, wait } = body || {};

  const finalPrompt = (prompt || characterPrompt || '').trim();
  jobCounter++;
  const job = {
    id: 'create_proj_' + jobCounter + '_' + Date.now(),
    rowId: rowId || row_id || null,
    projectId: null, // Will be generated by Flow
    sceneId: 'create_project_' + String(jobCounter).padStart(3, '0'),
    character: character || characterName || '',
    prompt: finalPrompt,
    images: images || [],
    action: 'create_project',
    callbackUrl: callbackUrl || null,
    status: 'QUEUED',
    createdAt: Date.now()
  };

  jobQueue.push(job);
  saveQueue();
  log('✨ Create project requested: ' + job.id + (images?.length ? ' [' + images.length + ' images]' : '') + (finalPrompt ? ' [Prompt: ' + finalPrompt.substring(0, 30) + '...]' : ''));

  dispatchNext();

  // If wait=true (default is true if wait !== false), wait synchronously up to 75s (if prompt) or 35s for projectId!
  const shouldWait = wait !== false;
  if (shouldWait) {
    const startWait = Date.now();
    const timeoutMs = finalPrompt ? 75000 : 35000;
    const checkDone = setInterval(() => {
      const found = completedJobs.find(j => j.id === job.id);
      if (found) {
        clearInterval(checkDone);
        return res.json({
          success: true,
          jobId: job.id,
          projectId: found.projectId || found.result?.projectId,
          character: found.result?.character || job.character,
          imageSrc: found.result?.imageSrc,
          status: 'completed',
          result: found.result
        });
      }

      const failed = failedJobs.find(j => j.id === job.id);
      if (failed) {
        clearInterval(checkDone);
        return res.status(500).json({
          success: false,
          jobId: job.id,
          status: 'failed',
          error: failed.error
        });
      }

      // Timeout
      if (Date.now() - startWait > timeoutMs) {
        clearInterval(checkDone);
        return res.json({
          success: true,
          jobId: job.id,
          status: 'processing',
          message: 'Project creation is taking longer than expected. Check /job/' + job.id + ' or your callbackUrl.'
        });
      }
    }, 500);
    return;
  }

  res.json({
    success: true,
    jobId: job.id,
    position: jobQueue.length,
    message: 'Create project job queued. Query /job/' + job.id + ' or wait for callback.'
  });
});

// Dedicated endpoint to create a character image (Imagen 3) in existing project or new project
app.post('/create-character', async (req, res) => {
  const body = Array.isArray(req.body) ? req.body[0] : req.body;
  const { rowId, row_id, projectId, character, characterName, prompt, characterPrompt, callbackUrl, wait } = body || {};

  const finalPrompt = (prompt || characterPrompt || '').trim();
  if (!finalPrompt) {
    return res.status(400).json({ error: 'Missing required field: prompt (or characterPrompt)' });
  }

  const finalChar = character || characterName || '';

  jobCounter++;
  const job = {
    id: 'char_' + (projectId || 'new') + '_' + jobCounter + '_' + Date.now(),
    rowId: rowId || row_id || null,
    projectId: projectId || null,
    sceneId: 'create_char_' + String(jobCounter).padStart(3, '0'),
    character: finalChar,
    prompt: finalPrompt,
    images: [],
    action: 'create_character',
    callbackUrl: callbackUrl || null,
    status: 'QUEUED',
    createdAt: Date.now()
  };

  jobQueue.push(job);
  saveQueue();
  log('🎨 Create character requested: ' + job.id + (finalChar ? ' [' + finalChar + ']' : '') + ' in project: ' + (job.projectId || '(new project)'));

  dispatchNext();

  const shouldWait = wait !== false;
  if (shouldWait) {
    const startWait = Date.now();
    const timeoutMs = 75000;
    const checkDone = setInterval(() => {
      const found = completedJobs.find(j => j.id === job.id);
      if (found) {
        clearInterval(checkDone);
        return res.json({
          success: true,
          jobId: job.id,
          projectId: found.projectId || found.result?.projectId,
          character: found.result?.character || job.character,
          imageSrc: found.result?.imageSrc,
          status: 'completed',
          result: found.result
        });
      }

      const failed = failedJobs.find(j => j.id === job.id);
      if (failed) {
        clearInterval(checkDone);
        return res.status(500).json({
          success: false,
          jobId: job.id,
          status: 'failed',
          error: failed.error
        });
      }

      // Timeout
      if (Date.now() - startWait > timeoutMs) {
        clearInterval(checkDone);
        return res.json({
          success: true,
          jobId: job.id,
          status: 'processing',
          message: 'Character generation is taking longer than expected. Check /job/' + job.id + ' or your callbackUrl.'
        });
      }
    }, 500);
    return;
  }

  res.json({
    success: true,
    jobId: job.id,
    position: jobQueue.length,
    message: 'Create character job queued. Query /job/' + job.id + ' or wait for callback.'
  });
});

// Query single job by ID to get projectId
app.get('/job/:jobId', (req, res) => {
  const { jobId } = req.params;

  // Check running job
  if (currentJob && currentJob.id === jobId) {
    return res.json({
      jobId: currentJob.id,
      status: currentJob.status || 'PROCESSING',
      state: currentJob.currentState
    });
  }

  // Check completed
  const completed = completedJobs.find(j => j.id === jobId);
  if (completed) {
    return res.json({
      jobId: completed.id,
      status: 'COMPLETED',
      projectId: completed.projectId || completed.result?.projectId,
      result: completed.result
    });
  }

  // Check failed
  const failed = failedJobs.find(j => j.id === jobId);
  if (failed) {
    return res.status(500).json({
      jobId: failed.id,
      status: 'FAILED',
      error: failed.error
    });
  }

  // Check in queue
  const queued = jobQueue.find(j => j.id === jobId);
  if (queued) {
    return res.json({
      jobId: queued.id,
      status: 'QUEUED',
      position: jobQueue.indexOf(queued) + 1
    });
  }

  res.status(404).json({ error: 'Job not found: ' + jobId });
});

// Get current status
app.get('/status', (req, res) => {
  res.json({
    extensionConnected: extensionSocket !== null && extensionSocket.readyState === WebSocket.OPEN,
    currentJob: currentJob,
    queueLength: jobQueue.length,
    queue: jobQueue.slice(0, 20),
    completedCount: completedJobs.length,
    recentCompleted: completedJobs.slice(0, 10),
    failedCount: failedJobs.length,
    recentFailed: failedJobs.slice(0, 10),
    paused: paused
  });
});

// Get queue details
app.get('/queue', (req, res) => {
  res.json({
    queue: jobQueue,
    currentJob: currentJob,
    paused: paused
  });
});

// Cancel a specific job
app.post('/cancel', (req, res) => {
  const { jobId } = req.body;

  // Cancel current job
  if (currentJob && currentJob.id === jobId) {
    log('🛑 Cancelling current job: ' + jobId);
    sendToExtension({ type: 'cancel_job', jobId: jobId });
    currentJob.status = 'CANCELLED';
    failedJobs.unshift(currentJob);
    currentJob = null;
    saveQueue();
    return res.json({ success: true, message: 'Current job cancelled' });
  }

  // Remove from queue
  const idx = jobQueue.findIndex(j => j.id === jobId);
  if (idx >= 0) {
    const removed = jobQueue.splice(idx, 1)[0];
    log('🗑️ Removed from queue: ' + jobId);
    saveQueue();
    return res.json({ success: true, message: 'Job removed from queue' });
  }

  res.status(404).json({ error: 'Job not found: ' + jobId });
});

// Pause queue
app.post('/pause', (req, res) => {
  paused = true;
  log('⏸️ Queue paused');
  sendToExtension({ type: 'pause' });
  res.json({ success: true, message: 'Queue paused' });
});

// Resume queue
app.post('/resume', (req, res) => {
  paused = false;
  log('▶️ Queue resumed');
  sendToExtension({ type: 'resume' });
  dispatchNext();
  res.json({ success: true, message: 'Queue resumed' });
});

// Clear completed/failed history and unstick queue
app.post('/clear-history', (req, res) => {
  completedJobs = [];
  failedJobs = [];
  if (currentJob) {
    log('⚠️ Forcefully clearing stuck currentJob');
    currentJob = null;
  }
  saveQueue();
  log('🧹 History and current job cleared');
  dispatchNext();
  res.json({ success: true });
});

// Retry a failed job
app.post('/retry', (req, res) => {
  const { jobId } = req.body;
  const idx = failedJobs.findIndex(j => j.id === jobId);
  if (idx >= 0) {
    const job = failedJobs.splice(idx, 1)[0];
    job.status = 'QUEUED';
    job.retryCount = (job.retryCount || 0) + 1;
    delete job.error;
    delete job.failedAt;
    jobQueue.push(job);
    saveQueue();
    dispatchNext();
    log('🔄 Retrying job: ' + jobId);
    return res.json({ success: true, message: 'Job re-queued' });
  }
  res.status(404).json({ error: 'Failed job not found: ' + jobId });
});

// ==========================================
// WEBSOCKET SERVER
// ==========================================
const server = http.createServer(app);
const wss = new WebSocketServer({ server });

wss.on('connection', (ws, req) => {
  log('🔗 WebSocket client connected from ' + req.socket.remoteAddress);

  ws.on('message', (raw) => {
    try {
      const msg = JSON.parse(raw.toString());
      handleExtensionMessage(ws, msg);
    } catch (e) {
      log('⚠️ Invalid message: ' + e.message);
    }
  });

  ws.on('close', () => {
    log('🔌 WebSocket client disconnected');
    if (extensionSocket === ws) {
      extensionSocket = null;
    }
  });

  ws.on('error', (err) => {
    log('❌ WebSocket error: ' + err.message);
  });

  // Ping-pong keepalive
  ws.isAlive = true;
  ws.on('pong', () => { ws.isAlive = true; });
});

// Keepalive interval
const heartbeat = setInterval(() => {
  wss.clients.forEach((ws) => {
    if (!ws.isAlive) {
      log('💀 Terminating unresponsive client');
      return ws.terminate();
    }
    ws.isAlive = false;
    ws.ping();
  });
}, 30000);

wss.on('close', () => clearInterval(heartbeat));

// ==========================================
// EXTENSION MESSAGE HANDLER
// ==========================================
function handleExtensionMessage(ws, msg) {
  switch (msg.type) {
    case 'register':
      extensionSocket = ws;
      log('✅ Extension registered');
      // Send pending jobs
      dispatchNext();
      break;

    case 'pong':
      // Keepalive response
      break;

    case 'job_queued':
      log('📋 Extension acknowledged job: ' + msg.jobId);
      break;

    case 'job_started':
      log('🚀 Extension started job: ' + msg.jobId);
      if (currentJob && currentJob.id === msg.jobId) {
        currentJob.status = 'PROCESSING';
        currentJob.startedAt = Date.now();
        saveQueue();
      }
      break;

    case 'state_update':
      log('📊 State: ' + msg.state + ' | Job: ' + (msg.jobId || '?') + ' | Retry: ' + (msg.retryCount || 0));
      if (currentJob && currentJob.id === msg.jobId) {
        currentJob.currentState = msg.state;
        currentJob.retryCount = msg.retryCount;
      }
      break;

    case 'job_completed':
      log('✅ Job completed: ' + msg.jobId);
      if (currentJob && currentJob.id === msg.jobId) {
        currentJob.status = 'COMPLETED';
        currentJob.completedAt = Date.now();
        currentJob.result = msg.result;
        completedJobs.unshift(currentJob);
        if (completedJobs.length > 100) completedJobs.pop();
        currentJob = null;
        saveQueue();

        // Callback to n8n
        sendCallback(msg);
      }
      // Process next
      setTimeout(dispatchNext, 2000);
      break;

    case 'job_failed':
      log('❌ Job failed: ' + msg.jobId + ' — ' + msg.error);
      if (currentJob && currentJob.id === msg.jobId) {
        currentJob.status = 'FAILED';
        currentJob.failedAt = Date.now();
        currentJob.error = msg.error;
        failedJobs.unshift(currentJob);
        if (failedJobs.length > 100) failedJobs.pop();
        currentJob = null;
        saveQueue();

        // Callback to n8n
        sendCallback(msg);
      }
      // Process next
      setTimeout(dispatchNext, 3000);
      break;

    default:
      log('⚠️ Unknown message type: ' + msg.type);
  }
}

// ==========================================
// JOB DISPATCH
// ==========================================
function dispatchNext() {
  if (paused) {
    log('⏸️ Queue paused, not dispatching');
    return;
  }
  if (currentJob) {
    log('⏳ Job already running: ' + currentJob.id);
    return;
  }
  if (jobQueue.length === 0) {
    log('📭 Queue empty');
    return;
  }
  if (!extensionSocket || extensionSocket.readyState !== WebSocket.OPEN) {
    log('⚠️ Extension not connected, waiting...');
    return;
  }

  currentJob = jobQueue.shift();
  currentJob.status = 'DISPATCHED';
  saveQueue();

  log('📤 Dispatching job: ' + currentJob.id);
  sendToExtension({
    type: 'new_job',
    job: {
      id: currentJob.id,
      rowId: currentJob.rowId,
      projectId: currentJob.projectId,
      sceneId: currentJob.sceneId,
      character: currentJob.character,
      prompt: currentJob.prompt,
      images: currentJob.images || [],
      action: currentJob.action || 'generate',
      callbackUrl: currentJob.callbackUrl,
      driveFolderId: currentJob.driveFolderId
    }
  });
}

function sendToExtension(msg) {
  if (extensionSocket && extensionSocket.readyState === WebSocket.OPEN) {
    extensionSocket.send(JSON.stringify(msg));
  } else {
    log('⚠️ Extension not connected');
  }
}

// ==========================================
// CALLBACK TO n8n
// ==========================================
async function sendCallback(result) {
  // Find original job to get callbackUrl
  const job = [...completedJobs, ...failedJobs].find(j => j.id === result.jobId);
  const callbackUrl = job?.callbackUrl || result.callbackUrl;

  if (!callbackUrl) {
    log('ℹ️ No callback URL for job: ' + result.jobId);
    return;
  }

  const payload = {
    jobId: result.jobId,
    rowId: result.rowId || job?.rowId || null,
    projectId: result.projectId,
    sceneId: result.sceneId,
    status: result.status || (result.type === 'job_completed' ? 'completed' : 'failed'),
    error: result.error || null,
    result: result.result || null,
    timestamp: Date.now()
  };

  // Retry callback up to 3 times
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await fetch(callbackUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      if (res.ok) {
        log('📤 Callback sent to ' + callbackUrl + ' (attempt ' + attempt + ')');
        return;
      }
      log('⚠️ Callback HTTP ' + res.status + ' (attempt ' + attempt + '/3)');
    } catch (e) {
      log('❌ Callback error (attempt ' + attempt + '/3): ' + e.message);
    }
    // Wait before retry
    if (attempt < 3) await new Promise(r => setTimeout(r, 2000 * attempt));
  }
  log('❌ All callback attempts failed for job: ' + result.jobId);
}

// ==========================================
// START SERVER
// ==========================================
loadQueue();

server.listen(PORT, () => {
  log('');
  log('╔══════════════════════════════════════════╗');
  log('║   Flow Auto Bridge v1.0                  ║');
  log('║   HTTP API + WebSocket: port ' + PORT + '        ║');
  log('╚══════════════════════════════════════════╝');
  log('');
  log('API Endpoints:');
  log('  POST /generate        — Submit new job');
  log('  GET  /status          — Current status');
  log('  GET  /queue           — Queue details');
  log('  POST /cancel          — Cancel job');
  log('  POST /pause           — Pause queue');
  log('  POST /resume          — Resume queue');
  log('  POST /retry           — Retry failed job');
  log('  POST /clear-history   — Clear history');
  log('');
  log('Waiting for extension connection...');
});
